apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrekNDQVRxZ0F3SUJBZ0lSQVB0dW81ekN3d1dzV1VPc09pSTZmNjh3Q2dZSUtvWkl6ajBFQXdJd0tERW0KTUNRR0ExVUVBeE1kZDJWaWFHOXZheTVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05Nakl3T1RFMgpNVGcwTlRJeldoY05Nekl3T1RFek1UZzBOVEl6V2pBb01TWXdKQVlEVlFRREV4MTNaV0pvYjI5ckxteHBibXRsCmNtUXVZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkdQZGpDSnkKUlYxR1d5eFNPR3hrQWVHdXFqa1JNVUFPTFFmZkRkd3dycXNlbzU1R09NTkg5YWQzUHc2ZTR3M1ZLS0g2QjBDLwordWIwSEdBUkcrL0RsdXlqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvCkFnRUJNQjBHQTFVZERnUVdCQlFSbHVWRHBmdnRmSmlRNCtFY2hyZ3k2WWFXbFRBS0JnZ3Foa2pPUFFRREFnTkgKQURCRUFpQXFnN0g0NEhXSEF5ZDhjckpHTDVLWHFhOG5wN1YySW5pVFdqV0FaK3RUMmdJZ0YzL0owekh4eDNxWgpXa0ZhL1JVYzlqVlVxblRLcXNmbGxJUDNZOWV0VFdzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBuc1Z2dENzTU5QNkFuYzMyNTF0S0oxNVhScTZoUFZidEpOWVE3TVVzdUlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWTkyTUluSkZYVVpiTEZJNGJHUUI0YTZxT1JFeFFBNHRCOThOM0RDdXF4Nmpua1k0dzBmMQpwM2MvRHA3akRkVW9vZm9IUUwvNjV2UWNZQkViNzhPVzdBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-issuer-tls
  namespace: linkerd
type: kubernetes.io/tls
