apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  source:
    path: linkerd-crds
    repoURL: 'https://github.com/irizzant/testlinkerd.git'
    targetRevision: main
    plugin:
      name: kustomized-remote-helm
      env:
        - name: HELM_REPO_URL
          value: "linkerd https://helm.linkerd.io/stable"
        - name: OPTIONS
          value: "--release-name linkerd linkerd/linkerd-crds"
  project: default
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - kind: Secret
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: "apps"
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: apiregistration.k8s.io
    kind: APIService
    jsonPointers:
    - /spec/caBundle
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/names/shortNames
