apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: linkerd
    repoURL: 'https://github.com/irizzant/testlinkerd.git'
    targetRevision: kustomize-old
    plugin:
      name: kustomized-remote-helm
      env:
      - name: HELM_REPO_URL
        value: "linkerd https://helm.linkerd.io/stable"
      - name: OPTIONS
        value: "--release-name linkerd -n linkerd --version 2.11.4 -f values-sdbit.yaml linkerd/linkerd2"      
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
