apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-100"

resources:
- ../../base
- argocd-ingress.yaml

patchesStrategicMerge:
- argo-cm-patch.yaml
- argo-rbac-patch.yaml
- argocd-repo-server-patch.yaml
